# Generated by Django 5.1.6 on 2025-02-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='compliance_framework',
            field=models.CharField(choices=[('SOC2', 'SOC2')], default='SOC2', max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='enforcement_type',
            field=models.CharField(choices=[('MANDATORY', 'Mandatory'), ('RECOMMENDED', 'Recommended'), ('OPTIONAL', 'Optional')], default='OPTIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='policyacknowledgmentstep',
            name='step_report_document',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='policystep',
            name='knowledge_document',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='policystepfield',
            name='field_value_type',
            field=models.CharField(choices=[('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('STRING', 'String'), ('DATETIME', 'DateTime')], default='STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='policytemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
